server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/checkdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: litianyi
  aop:
    auto: true
    proxy-target-class: true
#日志配置 无特殊需求无需更改
logging:
  config:  classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG
mybatis-plus:
  mapper-locations: classpath:com/poshing/checkdemo/mapper/**.xml
  type-aliases-package: com.poshing.checkdemo.entity
  configuration:
    jdbc-type-for-null: VARCHAR