server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/checkdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: litianyi
  aop:
    auto: true
    proxy-target-class: true
mybatis-plus:
  mapper-locations: classpath:com/poshing/checkdemo/mapper/**.xml
  type-aliases-package: com.poshing.checkdemo.entity
  configuration:
    jdbc-type-for-null: VARCHAR